server {
    listen 80;
    server_name localhost;

    # Essencial para o layout não quebrar:
    include /etc/nginx/mime.types;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Essencial para o Erro 404 e rotas do React:
        try_files $uri $uri/ /index.html;
    }
}