server {
    listen 80;
    server_name localhost;

    # Garante que o CSS e o JS não quebrem
    include /etc/nginx/mime.types;

    client_max_body_size 50M; 

    root /usr/share/nginx/html;
    index index.html index.htm;

    # 1. Proxy Reverso: Roteia chamadas da API internamente para o Backend (Ocultando a porta 5000)
    location /api/ {
        proxy_pass http://backend:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. React Router: Gerencia as telas do sistema
    location / {
        try_files $uri $uri/ /index.html;
    }
}